# Operations to get elements or properties of an array

In [1]:
import numpy as np

In [2]:
an_array = np.arange(0,11)
print(an_array)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [3]:
first_element = an_array[0]
print(first_element)
last_element = an_array[-1]
print(last_element)

0
10


In [4]:
first_five = an_array[0:5]
print(first_five)

[0 1 2 3 4]


In [7]:
last_five = an_array[6::2]
print(last_five)

[ 6  8 10]


In [8]:
first_five_reversed = an_array[4::-1]
print(first_five_reversed)

[4 3 2 1 0]


In [11]:
final_two = an_array[-2:]
print(final_two)

[ 9 10]


In [12]:
print(an_array.size)

11


In [13]:
print(np.amax(an_array))

10


In [14]:
print(np.amin(an_array))

0


In [15]:
print(np.average(an_array))

5.0
