# Modify elements & properties of arrays

In [1]:
import numpy as np

In [2]:
an_array = np.arange(0,6)
print(an_array)

[0 1 2 3 4 5]


In [3]:
an_array[0] = 10
print(an_array)

[10  1  2  3  4  5]


In [6]:
an_array = np.arange(0,6)
print(np.append(an_array, 6))

[0 1 2 3 4 5 6]


In [8]:
print(np.append(an_array, [6,7]))

[0 1 2 3 4 5 6 7]


In [9]:
print(np.insert(an_array, 0, [10,11]))

[10 11  0  1  2  3  4  5]


In [10]:
print(np.insert(an_array, 1, [10,11]))

[ 0 10 11  1  2  3  4  5]


In [11]:
print(np.delete(an_array, 3))

[0 1 2 4 5]


In [12]:
print(an_array * 2)

[ 0  2  4  6  8 10]


In [13]:
print(an_array + 2)

[2 3 4 5 6 7]


In [14]:
another_array = np.array([3,6,21,9,10,1])
print(np.sort(another_array))

[ 1  3  6  9 10 21]


In [15]:
print(-np.sort(-another_array))

[21 10  9  6  3  1]
